[package]
name = "rust_volleyball"
version = "0.1.0"
edition = "2024"

[dependencies]
rapier2d = {version = "0.23.0"}
macroquad = {version = "0.4.13"}
log = "0.4.26"
env_logger = "0.11.6"
tokio = { version = "1.43.0", features = ["rt", "net", "io-util"] }
rand = "0.9.0"
